import type { Lead, Maintenance, Project } from "@/lib/types"
import { createDefaultTasks } from "@/lib/templates"

function iso(offsetDays: number): string {
  const d = new Date()
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().slice(0, 10)
}

function withCompletedTasks(count: number) {
  const tasks = createDefaultTasks()
  return tasks.map((t, i) => (i < count ? { ...t, done: true } : t))
}

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "proj_bloom",
    businessName: "Bloom Cafe",
    clientName: "Maria Santos",
    contact: "maria@bloomcafe.ph",
    businessType: "Restaurant / Cafe",
    projectName: "Bloom Cafe Website",
    description: "Menu, gallery, and online reservations for a neighborhood cafe.",
    price: 15000,
    depositPercentage: 40,
    startDate: iso(-20),
    targetDate: iso(10),
    status: "building",
    tasks: withCompletedTasks(12),
    payments: [
      {
        id: "pay_bloom_1",
        description: "Deposit (40%)",
        amount: 6000,
        dueDate: iso(-20),
        datePaid: iso(-19),
        status: "paid",
      },
      {
        id: "pay_bloom_2",
        description: "Final payment (60%)",
        amount: 9000,
        dueDate: iso(10),
        datePaid: null,
        status: "pending",
      },
    ],
    changes: [
      {
        id: "chg_bloom_1",
        description: "Add online ordering integration",
        additionalCost: 3500,
        additionalDays: 5,
        date: iso(-5),
        status: "approved",
      },
    ],
    notes: [
      {
        id: "note_bloom_1",
        content: "Client prefers warm earthy tones. Waiting on final food photos.",
        date: iso(-8),
      },
    ],
    technical: {
      domain: "bloomcafe.ph",
      hosting: "Vercel",
      repository: "github.com/dev/bloom-cafe",
      techStack: "Next.js, Tailwind CSS",
      credentials: "Domain registrar login shared via password manager.",
    },
  },
  {
    id: "proj_torres",
    businessName: "Torres Dental Clinic",
    clientName: "Dr. Ramon Torres",
    contact: "0917 555 2211",
    businessType: "Healthcare",
    projectName: "Clinic Booking Site",
    description: "Appointment booking and services page for a dental clinic.",
    price: 28000,
    depositPercentage: 50,
    startDate: iso(-8),
    targetDate: iso(25),
    status: "client_review",
    tasks: withCompletedTasks(18),
    payments: [
      {
        id: "pay_torres_1",
        description: "Deposit (50%)",
        amount: 14000,
        dueDate: iso(-8),
        datePaid: iso(-7),
        status: "paid",
      },
      {
        id: "pay_torres_2",
        description: "Final payment (50%)",
        amount: 14000,
        dueDate: iso(25),
        datePaid: null,
        status: "pending",
      },
    ],
    changes: [],
    notes: [
      {
        id: "note_torres_1",
        content: "Homepage sent for review. Awaiting feedback on hero copy.",
        date: iso(-2),
      },
    ],
    technical: {
      domain: "torresdental.ph",
      hosting: "Vercel",
      repository: "github.com/dev/torres-dental",
      techStack: "Next.js, Supabase",
      credentials: "",
    },
  },
  {
    id: "proj_kalye",
    businessName: "Kalye Coffee Roasters",
    clientName: "Ivan dela Cruz",
    contact: "ivan@kalyeroasters.com",
    businessType: "Retail / E-commerce",
    projectName: "Coffee Shop Online Store",
    description: "Product catalog and checkout for a local coffee roaster.",
    price: 42000,
    depositPercentage: 40,
    startDate: iso(-2),
    targetDate: iso(40),
    status: "deposit_paid",
    tasks: withCompletedTasks(4),
    payments: [
      {
        id: "pay_kalye_1",
        description: "Deposit (40%)",
        amount: 16800,
        dueDate: iso(-2),
        datePaid: iso(-1),
        status: "paid",
      },
      {
        id: "pay_kalye_2",
        description: "Final payment (60%)",
        amount: 25200,
        dueDate: iso(40),
        datePaid: null,
        status: "pending",
      },
    ],
    changes: [],
    notes: [],
    technical: {
      domain: "",
      hosting: "",
      repository: "",
      techStack: "Next.js, Stripe",
      credentials: "",
    },
  },
  {
    id: "proj_verde",
    businessName: "Verde Landscaping",
    clientName: "Grace Lim",
    contact: "grace@verde.ph",
    businessType: "Services",
    projectName: "Landscaping Portfolio Site",
    description: "Portfolio and quote request form for a landscaping business.",
    price: 18000,
    depositPercentage: 40,
    startDate: iso(-45),
    targetDate: iso(-5),
    status: "final_payment",
    tasks: withCompletedTasks(22),
    payments: [
      {
        id: "pay_verde_1",
        description: "Deposit (40%)",
        amount: 7200,
        dueDate: iso(-45),
        datePaid: iso(-44),
        status: "paid",
      },
      {
        id: "pay_verde_2",
        description: "Final payment (60%)",
        amount: 10800,
        dueDate: iso(-3),
        datePaid: null,
        status: "pending",
      },
    ],
    changes: [],
    notes: [
      {
        id: "note_verde_1",
        content: "Site approved. Final invoice sent, awaiting payment.",
        date: iso(-3),
      },
    ],
    technical: {
      domain: "verde.ph",
      hosting: "Vercel",
      repository: "github.com/dev/verde",
      techStack: "Next.js, Tailwind CSS",
      credentials: "Handover pending final payment.",
    },
  },
  {
    id: "proj_aning",
    businessName: "Aning Handmade",
    clientName: "Bea Reyes",
    contact: "bea@aninghandmade.com",
    businessType: "Retail / E-commerce",
    projectName: "Craft Store Website",
    description: "Simple brochure site with product highlights and contact.",
    price: 12000,
    depositPercentage: 50,
    startDate: iso(-90),
    targetDate: iso(-60),
    status: "completed",
    tasks: withCompletedTasks(24),
    payments: [
      {
        id: "pay_aning_1",
        description: "Deposit (50%)",
        amount: 6000,
        dueDate: iso(-90),
        datePaid: iso(-89),
        status: "paid",
      },
      {
        id: "pay_aning_2",
        description: "Final payment (50%)",
        amount: 6000,
        dueDate: iso(-60),
        datePaid: iso(-58),
        status: "paid",
      },
    ],
    changes: [],
    notes: [],
    technical: {
      domain: "aninghandmade.com",
      hosting: "Vercel",
      repository: "github.com/dev/aning",
      techStack: "Next.js, Tailwind CSS",
      credentials: "All credentials transferred to client.",
    },
  },
]

export const SAMPLE_LEADS: Lead[] = [
  {
    id: "lead_1",
    businessName: "Sunrise Bakery",
    businessType: "Restaurant / Cafe",
    contact: "sunrise@gmail.com",
    potentialValue: 20000,
    lastContact: iso(-3),
    nextFollowUp: iso(2),
    notes: "Interested in a menu site with online orders.",
    status: "interested",
  },
  {
    id: "lead_2",
    businessName: "Metro Fitness Gym",
    businessType: "Fitness",
    contact: "0918 222 3344",
    potentialValue: 35000,
    lastContact: iso(-1),
    nextFollowUp: iso(4),
    notes: "Sent proposal for booking + class schedule site.",
    status: "proposal_sent",
  },
  {
    id: "lead_3",
    businessName: "Cebu Travel Co.",
    businessType: "Travel / Tourism",
    contact: "hello@cebutravel.ph",
    potentialValue: 50000,
    lastContact: iso(-7),
    nextFollowUp: iso(1),
    notes: "Wants a tour booking platform. Big potential.",
    status: "contacted",
  },
  {
    id: "lead_4",
    businessName: "Juan's Auto Repair",
    businessType: "Services",
    contact: "juan.auto@gmail.com",
    potentialValue: 15000,
    lastContact: iso(-10),
    nextFollowUp: iso(-1),
    notes: "New inquiry from referral.",
    status: "new",
  },
]

export const SAMPLE_MAINTENANCE: Maintenance[] = [
  {
    id: "maint_1",
    client: "Bea Reyes",
    website: "aninghandmade.com",
    plan: "Basic Care",
    monthlyFee: 1500,
    nextBilling: iso(12),
    status: "active",
    lastActivity: "Monthly backup + plugin updates",
  },
  {
    id: "maint_2",
    client: "Cardo Enterprises",
    website: "cardoent.ph",
    plan: "Standard Care",
    monthlyFee: 2500,
    nextBilling: iso(3),
    status: "active",
    lastActivity: "Content update on homepage",
  },
  {
    id: "maint_3",
    client: "Lola's Kitchen",
    website: "lolaskitchen.ph",
    plan: "Basic Care",
    monthlyFee: 1500,
    nextBilling: iso(-2),
    status: "paused",
    lastActivity: "Client requested a short pause",
  },
]
